name: mac

on: 
  push:

jobs:

  build-mac:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        cd ../..
        git clone https://github.com/open-ephys/plugin-GUI.git --branch testing
        cd plugin-GUI/Build && cmake -G "Xcode" ..
    - name: build
      run: |
        cd Build
        cmake -G "Xcode" ..
        xcodebuild -configuration Release
        install_name_tool -change /usr/local/lib/libhdf5.10.dylib @loader_path/libhdf5.10.dylib Release/libOpenEphysHDF5.dylib
        install_name_tool -change /usr/local/lib/libhdf5_cpp.15.dylib @loader_path/libhdf5_cpp.15.dylib Release/libOpenEphysHDF5.dylib
#    - name: test
#      run: cd build && ctest
    - name: deploy
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
        build_dir: "Build/Release"
        repo: ${{ github.event.repository.name }}
        package: ${{ github.event.repository.name }}-mac
      run: |
        plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]" | tail -1)
        tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        new_plugin_ver=$tag-API$plugin_api
        mkdir shared 
        cp -r $build_dir/*.dylib shared
        cp -r libs/macos/bin/* shared
        zipfile=${package}_${new_plugin_ver}.zip
        zip -r -X $zipfile shared
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/$bintrayUser/$repo/$package/$new_plugin_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/$bintrayUser/$repo/$package/$new_plugin_ver/publish